name: Deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche l'action lorsque vous poussez sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  # This line ensures that submodules are checked out

    - name: Install Zola
      run: |
        curl -L https://github.com/getzola/zola/releases/download/v0.15.2/zola-v0.15.2-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C /usr/local/bin

    - name: Build the site
      run: zola build --output-dir build

    - name: Show generated files
      run: ls -R public

    - name: Show the content of style.css
      run: cat public/style.css

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build