name: Deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche l'action lorsque vous poussez sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Zola
        run: |
          curl -L https://github.com/getzola/zola/releases/download/v0.16.1/zola-v0.16.1-x86_64-unknown-linux-gnu.tar.gz --output zola.tar.gz
          tar -xzf zola.tar.gz
          sudo mv zola /usr/local/bin/

      - name: Build the site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public